Int tests
kwilteam/kwil-db pull request #1177
Opened 2024-12-20 16:14 UTC by charithabandi

2025-01-02 16:43 UTC, jchappelow requested changes
Looks good. Thanks for updating the integ composes.  `task dev:testnet:up` works as expected.  However in the the `r.t.Failed()` condition, I do not think we want a 5 minute sleep.  The containers can just be stopped because with a `Stop` of each container rather than `dc.Down` they won't be deleted, and we can still see the container logs, or even start them again manually.

2025-01-02 16:43 UTC, jchappelow commented on test/integration/helper.go
> +			time.Sleep(5 * time.Minute)
I don't think we want CI to hang for 5 min on failure, which is what will happen now, I believe.

2025-01-03 19:02 UTC, charithabandi commented on test/integration/helper.go
> +			time.Sleep(5 * time.Minute)
Ah, I changed it for testing, forgot to change it back. Oops!

2025-01-06 15:49 UTC, jchappelow approved these changes

2025-01-06 15:49 UTC, merged